[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
codespan-reporting = "0.11.1"
cranelift-codegen = "0.78.0"
cranelift-frontend = "0.78.0"
cranelift-module = "0.78.0"
cranelift-object = "0.78.0"
cranelift-native = "0.78.0"
rustc-hash = "1.1.0"

[dependencies.fuzzcheck]
version = "0.10.1"
optional = true

[dev-dependencies]
codegen = { path = "../tests/codegen" }
insta = "1.8.0"
rustversion = "1.0.6"
serde = { version = "1.0.131", features = ["derive"] }
