[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
codespan-reporting = "0.11.1"
cranelift-codegen = "0.77.0"
cranelift-frontend = "0.77.0"
cranelift-module = "0.77.0"
cranelift-object = "0.77.0"
cranelift-native = "0.77.0"
rustc-hash = "1.1.0"

[dev-dependencies]
codegen = { path = "../tests/codegen" }
fuzzcheck = "0.8.0"
insta = "1.8.0"
rustversion = "1.0.5"
serde = { version = "1.0.130", features = ["derive"] }
