[package]
name = "logic"
version = "0.1.0"
edition = "2018"

[features]
_proptest = ["proptest"]

[dependencies]
proptest = { version = "1.0.0", optional = true }

[dev-dependencies]
codegen = { path = "../tests/codegen" }
insta = "1.8.0"
rustversion = "1.0.5"
