[package]
name = "logic"
version = "0.1.0"
edition = "2018"

[features]
_proptest = ["proptest"]

[dependencies]
proptest = { version = "1.0.0", optional = true }
z3 = "0.10"

[dev-dependencies]
codegen = { path = "../tests/codegen" }
insta = "1.7.1"
