[tasks.fuzz_ci]
run_task = [{name="fuzz_parser_ci"}, {name="fuzz_unifier_ci"}]

[tasks.fuzz_parser_ci]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "parse::fuzz::fuzz_parser",
    "fuzz",
    "--artifacts",
    "fuzz/artifacts",
    "-max-duration",
    "300"
]

[tasks.fuzz_parser]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "parse::fuzz::fuzz_parser",
    "fuzz",
    "--artifacts",
    "fuzz/artifacts",
]

[tasks.fuzz_unifier_ci]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "ty::fuzz::fuzz_unifier",
    "fuzz",
    "--artifacts",
    "fuzz/artifacts",
    "-max-duration",
    "300"
]

[tasks.fuzz_unifier]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "ty::fuzz::fuzz_unifier",
    "fuzz",
    "--artifacts",
    "fuzz/artifacts",
]

[tasks.tests]
command = "cargo"
toolchain = "nightly"
args = [
    "test"
]
env = { "RUSTFLAGS" = "--cfg=disable_fuzzcheck" }
