[tasks.fuzz_parser]
command = "cargo"
toolchain = "nightly"
args = [
    "fuzzcheck",
    "parse::fuzz::fuzz_parser",
    "fuzz",
    "--artifacts",
    "fuzz/artifacts",
]

[tasks.tests]
command = "cargo"
toolchain = "nightly"
args = [
    "test"
]
env = { "RUSTFLAGS" = "--cfg=disable_fuzzcheck" }
